name: CI devops 2023 - Deployment

# Ce pipeline ne sera déclenché que lorsque le pipeline de test réussit
on:
  workflow_run:
    workflows: ["CI devops 2023 - Test"]
    branches: main
    types:
      - completed

jobs:
  build-and-push-docker-image:
    # N'exécuter ce job que si le pipeline de test a réussi ET si on est sur la branche main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan edwin.helet.takima.cloud >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      

      - name: Install Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install ansible -y

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
        

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build image and push http-server
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-http-server:latest
          push: true
      
      - name: Build image and push devops-front
        uses: docker/build-push-action@v3
        with:
          context: ./devops-front
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-devops-front:latest
          push: true
